name: Deploy

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_APIKEY }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment: development

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_email: michal.miladowski@gmail.com
        heroku_api_key: ${{ secrets.HEROKU_APIKEY }}
        heroku_app_name: node-ga-${{ github.run_id }}
        usedocker: true
    - name: Test connection
      run: sleep 10 && curl -s https://node-ga-${{ github.run_id }}.herokuapp.com | grep -q OK...
#     - name: Destroy app
#       if: always()
#       run: heroku apps:destroy --app node-ga-${{ github.run_id }} --confirm=node-ga-${{ github.run_id }}
