name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm test 2>&1 | tee unitlog.txt
    - name: Update test results
      run: |
        git config --global user.name 'Ghost'
        git config --global user.email 'michal.miladowski@gmail.com'
        git add unitlog.txt
        git commit -am 'Updated test results'
        git push
