name: Recurring tasks

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: UnitLogs cleanup
        run: sh .github/workflows-scripts/clean-unitlogs.sh
