name: Run tests

on:
  push:
    branches: [ main ] 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Install project dependencies
      run: npm ci
    - name: Run tests
      run: npm test 2>&1 | tee result.txt
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: result.txt
        retention-days: 1
