name: Run tests

on:
  push:
    branches: [ main ] 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Install project dependencies
      run: npm ci
    - name: Run tests
      id: tests
      run: |
        set -o pipefail
        npm test 2>&1 | tee result.txt
        echo "::set-output name=date::$(date "+%Y-%m-%d %H:%M:%S")"
    - name: Create issue if unit tests failed
      if: failure()
      uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ secrets.github_token }}
        title: ${{ steps.tests.outputs.date }}
        body: |
          costam
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: result.txt
        retention-days: 1
