name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    environment: Secrets

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Install project dependencies
      run: npm ci
    - name: Run tests
      run: |
        set -o pipefail
        npm test 2>&1 | tee result.txt
    - name: Build docker image
      run: docker build -t $DOCKER_USER/$DOCKER_REPOSITORY:${{ github.run_id }} .
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
    - name: Log into docker repository
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
    - name: Push docker image
      run: docker push $DOCKER_USER/$DOCKER_REPOSITORY:${{ github.run_id }}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: result.txt
        retention-days: 1
    - name: Gather information for issue if failure
      id: issueinfo
      if: failure()
      run: |
        echo "::set-output name=date::$(date "+%Y-%m-%d %H:%M:%S")"
        RESULT=$(cat result.txt)
        RESULT="${RESULT//'%'/'%25'}"
        RESULT="${RESULT//$'\n'/'%0A'}"
        RESULT="${RESULT//$'\r'/'%0D'}"
        echo "::set-output name=file::$RESULT"
    - name: Create issue if failure
      if: failure()
      uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ secrets.github_token }}
        title: Unit tests failed (${{ github.actor }}, ${{ steps.issueinfo.outputs.date }}, ${{ github.run_id }})
        body: |
          ${{ steps.issueinfo.outputs.file }}
